#ifndef RADIOCORE_BOARD_HELTEC_RC52_H
#define RADIOCORE_BOARD_HELTEC_RC52_H

#include <Arduino.h>
#include <SPI.h>
#include <Wire.h>

#define RADIOCORE_HAS_SENSOR_I2C 1
#define RADIOCORE_SENSOR_I2C_INSTANCE Wire
#define RADIOCORE_SENSOR_I2C_SDA (32 + 11) // P1.11
#define RADIOCORE_SENSOR_I2C_SCL (0 + 2)   // P0.02
#define RADIOCORE_SENSOR_I2C_DEFAULT_FREQUENCY 100000UL

#define RADIOCORE_HAS_MMC5983MA 1
#define RADIOCORE_HAS_ICM42607P 1

#define RADIOCORE_HAS_SENSOR_POWER_CTRL 1
#define RADIOCORE_SENSOR_POWER_CTRL_PIN (0 + 12)
#define RADIOCORE_SENSOR_POWER_ON HIGH
#define RADIOCORE_SENSOR_POWER_WARMUP_MS 100UL

#define RADIOCORE_HAS_SENSOR_RESET 1
#define RADIOCORE_SENSOR_RESET_PIN (32 + 15) // P1.15
#define RADIOCORE_SENSOR_RESET_RELEASE_LEVEL HIGH

#define RADIOCORE_HAS_ROTARY_ENCODER 1
#define RADIOCORE_ROTARY_ENCODER_I2C_ADDRESS 0x20
#define RADIOCORE_ROTARY_ENCODER_PHASE_A_MASK 0x01
#define RADIOCORE_ROTARY_ENCODER_PHASE_B_MASK 0x02

#define RADIOCORE_HAS_USER_BUTTON 1
#define RADIOCORE_USER_BUTTON_PIN (32 + 10) // P1.10
#define RADIOCORE_USER_BUTTON_ACTIVE_LEVEL LOW
#define RADIOCORE_USER_BUTTON_PIN_MODE INPUT_PULLUP

#define RADIOCORE_HAS_CH01_ADC 1
#define RADIOCORE_CH01_ADC_PIN 2
#define RADIOCORE_HAS_CH01_POWER_CTRL 0

#define RADIOCORE_HAS_VO01_ADC 1
#define RADIOCORE_VO01_ADC_PIN 2
#define RADIOCORE_HAS_VO01_POWER_CTRL 0

#define RADIOCORE_HAS_CO01_ADC 1
#define RADIOCORE_CO01_ADC_PIN 2
#define RADIOCORE_CO01_CONTROL_PIN 21
#define RADIOCORE_HAS_CO01_POWER_CTRL 0

#define RADIOCORE_HAS_SOIL_MOISTURE_ADC 1
#define RADIOCORE_SOIL_MOISTURE_ADC_PIN (32 + 13) // P1.13
#define RADIOCORE_HAS_SOIL_MOISTURE_POWER_CTRL 1
#define RADIOCORE_SOIL_MOISTURE_POWER_CTRL_PIN (0 + 9) // P0.09
#define RADIOCORE_SOIL_MOISTURE_POWER_ON HIGH
#define RADIOCORE_SOIL_MOISTURE_POWER_WARMUP_MS 100UL

#define RADIOCORE_HAS_NV3001B_DISPLAY 1
#define RADIOCORE_NV3001B_BOARD_NAME "Heltec RC52"
#define RADIOCORE_NV3001B_USE_ESP32_SPI 0
#define RADIOCORE_NV3001B_USE_HARDWARE_SPI 1
#define RADIOCORE_NV3001B_USE_SOFTWARE_SPI 0
#define RADIOCORE_NV3001B_SPI_INSTANCE SPI1
#define RADIOCORE_NV3001B_SPI_MISO PIN_SPI1_MISO
#define RADIOCORE_NV3001B_SCK (0 + 30)
#define RADIOCORE_NV3001B_MOSI (32 + 2)
#define RADIOCORE_NV3001B_CS (32 + 4)
#define RADIOCORE_NV3001B_DC (0 + 28)
#define RADIOCORE_NV3001B_RST (0 + 10)
#define RADIOCORE_NV3001B_ENABLE (32 + 13)
#define RADIOCORE_NV3001B_ENABLE_ACTIVE LOW
#define RADIOCORE_NV3001B_BACKLIGHT (0 + 9)
#define RADIOCORE_NV3001B_BACKLIGHT_ACTIVE HIGH
#define RADIOCORE_NV3001B_SPI_FREQUENCY 8000000UL

#define RADIOCORE_HAS_WS2812 1
#define RADIOCORE_WS2812_DATA_PIN (0 + 9) // P0.09

#define RADIOCORE_HAS_BUZZER 1
#define RADIOCORE_BUZZER_PIN (0 + 5) // P0.05

#define RADIOCORE_HAS_MOTOR_CONTROL 1
#define RADIOCORE_MOTOR_IN1_PIN (32 + 1) // P1.01
#define RADIOCORE_MOTOR_IN2_PIN (0 + 20) // P0.20

#define RADIOCORE_HAS_RELAY_CONTROL 1
#define RADIOCORE_RELAY_CONTROL_PIN (32 + 15) // P1.15
#define RADIOCORE_RELAY_ACTIVE_LEVEL HIGH

#define RADIOCORE_HAS_SERVO_CONTROL 1
#define RADIOCORE_SERVO_PWM1_PIN (32 + 1) // P1.01
#define RADIOCORE_SERVO_PWM2_PIN (0 + 20) // P0.20
#define RADIOCORE_SERVO_ENABLE_PIN (32 + 6) // P1.06
#define RADIOCORE_SERVO_ENABLE_ACTIVE_LEVEL HIGH

#endif // RADIOCORE_BOARD_HELTEC_RC52_H
