#ifndef RADIOCORE_BOARD_HELTEC_RC32_H
#define RADIOCORE_BOARD_HELTEC_RC32_H

#include <Arduino.h>
#include <SPI.h>
#include <Wire.h>

#define RADIOCORE_HAS_SENSOR_I2C 1
#define RADIOCORE_SENSOR_I2C_INSTANCE Wire
#define RADIOCORE_SENSOR_I2C_SDA 21
#define RADIOCORE_SENSOR_I2C_SCL 18
#define RADIOCORE_SENSOR_I2C_DEFAULT_FREQUENCY 100000UL

#define RADIOCORE_HAS_SENSOR_POWER_CTRL 1
#define RADIOCORE_SENSOR_POWER_CTRL_PIN 46
#define RADIOCORE_SENSOR_POWER_ON HIGH
#define RADIOCORE_SENSOR_POWER_WARMUP_MS 100UL

#define RADIOCORE_HAS_ROTARY_ENCODER 1
#define RADIOCORE_ROTARY_ENCODER_I2C_ADDRESS 0x20
#define RADIOCORE_ROTARY_ENCODER_PHASE_A_MASK 0x01
#define RADIOCORE_ROTARY_ENCODER_PHASE_B_MASK 0x02

#define RADIOCORE_HAS_USER_BUTTON 1
#define RADIOCORE_USER_BUTTON_PIN 0
#define RADIOCORE_USER_BUTTON_ACTIVE_LEVEL LOW
#define RADIOCORE_USER_BUTTON_PIN_MODE INPUT_PULLUP

#define RADIOCORE_HAS_CH01_ADC 1
#define RADIOCORE_CH01_ADC_PIN 2
#define RADIOCORE_HAS_CH01_POWER_CTRL 1
#define RADIOCORE_CH01_POWER_CTRL_PIN 46
#define RADIOCORE_CH01_POWER_ON HIGH
#define RADIOCORE_CH01_POWER_WARMUP_MS 100UL

#define RADIOCORE_HAS_VO01_ADC 1
#define RADIOCORE_VO01_ADC_PIN 2
#define RADIOCORE_HAS_VO01_POWER_CTRL 1
#define RADIOCORE_VO01_POWER_CTRL_PIN 46
#define RADIOCORE_VO01_POWER_ON HIGH
#define RADIOCORE_VO01_POWER_WARMUP_MS 100UL

#define RADIOCORE_HAS_CO01_ADC 1
#define RADIOCORE_CO01_ADC_PIN 2
#define RADIOCORE_CO01_CONTROL_PIN 21
#define RADIOCORE_HAS_CO01_POWER_CTRL 1
#define RADIOCORE_CO01_POWER_CTRL_PIN 46
#define RADIOCORE_CO01_POWER_ON HIGH
#define RADIOCORE_CO01_POWER_WARMUP_MS 100UL

#define RADIOCORE_HAS_SOIL_MOISTURE_ADC 1
#define RADIOCORE_SOIL_MOISTURE_ADC_PIN 6
#define RADIOCORE_HAS_SOIL_MOISTURE_POWER_CTRL 1
#define RADIOCORE_SOIL_MOISTURE_POWER_CTRL_PIN 5
#define RADIOCORE_SOIL_MOISTURE_POWER_ON HIGH
#define RADIOCORE_SOIL_MOISTURE_POWER_WARMUP_MS 100UL

#define RADIOCORE_HAS_NV3001B_DISPLAY 1
#define RADIOCORE_NV3001B_BOARD_NAME "Heltec RC32"
#define RADIOCORE_NV3001B_USE_ESP32_SPI 1
#define RADIOCORE_NV3001B_USE_HARDWARE_SPI 0
#define RADIOCORE_NV3001B_USE_SOFTWARE_SPI 0
#define RADIOCORE_NV3001B_SPI_HOST FSPI
#define RADIOCORE_NV3001B_SCK 17
#define RADIOCORE_NV3001B_MOSI 38
#define RADIOCORE_NV3001B_MISO -1
#define RADIOCORE_NV3001B_CS 39
#define RADIOCORE_NV3001B_DC 16
#define RADIOCORE_NV3001B_RST 4
#define RADIOCORE_NV3001B_ENABLE 6
#define RADIOCORE_NV3001B_ENABLE_ACTIVE LOW
#define RADIOCORE_NV3001B_BACKLIGHT 5
#define RADIOCORE_NV3001B_BACKLIGHT_ACTIVE HIGH
#define RADIOCORE_NV3001B_SPI_FREQUENCY 8000000UL

#define RADIOCORE_HAS_WS2812 1
#define RADIOCORE_WS2812_DATA_PIN 5

#define RADIOCORE_HAS_BUZZER 1
#define RADIOCORE_BUZZER_PIN 48

#define RADIOCORE_HAS_MOTOR_CONTROL 1
#define RADIOCORE_MOTOR_IN1_PIN 41
#define RADIOCORE_MOTOR_IN2_PIN 42

#define RADIOCORE_HAS_RELAY_CONTROL 1
#define RADIOCORE_RELAY_CONTROL_PIN 2
#define RADIOCORE_RELAY_ACTIVE_LEVEL HIGH

#define RADIOCORE_HAS_SERVO_CONTROL 1
#define RADIOCORE_SERVO_PWM1_PIN 41
#define RADIOCORE_SERVO_PWM2_PIN 42
#define RADIOCORE_SERVO_ENABLE_PIN 40
#define RADIOCORE_SERVO_ENABLE_ACTIVE_LEVEL HIGH

#endif // RADIOCORE_BOARD_HELTEC_RC32_H
