#ifndef RADIOCORE_BOARD_CONFIG_H
#define RADIOCORE_BOARD_CONFIG_H

#if defined(HELTEC_RC52)
#include "boards/heltec_rc52.h"
#elif defined(HELTEC_RC32)
#include "boards/heltec_rc32.h"
#elif defined(HELTEC_RCC6)
#include "boards/heltec_rcc6.h"
#else
#define RADIOCORE_HAS_SENSOR_I2C 0
#define RADIOCORE_HAS_SENSOR_POWER_CTRL 0
#define RADIOCORE_HAS_CH01_ADC 0
#define RADIOCORE_HAS_CH01_POWER_CTRL 0
#define RADIOCORE_HAS_VO01_ADC 0
#define RADIOCORE_HAS_VO01_POWER_CTRL 0
#define RADIOCORE_HAS_CO01_ADC 0
#define RADIOCORE_HAS_CO01_POWER_CTRL 0
#define RADIOCORE_HAS_SOIL_MOISTURE_ADC 0
#define RADIOCORE_HAS_SOIL_MOISTURE_POWER_CTRL 0
#define RADIOCORE_HAS_NV3001B_DISPLAY 0
#define RADIOCORE_NV3001B_USE_ESP32_SPI 0
#define RADIOCORE_NV3001B_USE_HARDWARE_SPI 0
#define RADIOCORE_NV3001B_USE_SOFTWARE_SPI 0
#define RADIOCORE_HAS_WS2812 0
#define RADIOCORE_HAS_BUZZER 0
#define RADIOCORE_HAS_MOTOR_CONTROL 0
#define RADIOCORE_HAS_RELAY_CONTROL 0
#define RADIOCORE_HAS_SERVO_CONTROL 0
#define RADIOCORE_HAS_ROTARY_ENCODER 0
#define RADIOCORE_HAS_USER_BUTTON 0
#endif

#endif // RADIOCORE_BOARD_CONFIG_H
